extern u64 gGiKindlingPackDL_pack_fabric_ci4[];
extern u64 gGiKindlingPackDL_pack_fabric_pal_rgba16[];
extern Vtx gGiKindlingPackDL_gGiKindlingPackDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gGiKindlingPackDL_gGiKindlingPackDL_mesh_layer_Opaque_vtx_0[186];
extern Gfx gGiKindlingPackDL_gGiKindlingPackDL_mesh_layer_Opaque_tri_0[];
extern Gfx mat_gGiKindlingPackDL_f3dlite_material_001_layerOpaque[];
extern Gfx gGiKindlingPackDL[];
